AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation for a simple calculator Lambda function and static website hosting on S3.

Parameters:
  HtmlFileUrl:
    Type: String
    Default: https://raw.githubusercontent.com/hasherwi/calculator/main/calculator-page.html
    Description: URL of the HTML file to be uploaded to the S3 bucket.

Resources:
  CalculatorLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_handler
      Role: !GetAtt CalculatorLambdaFunctionExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              operation = event.get('operation', 'add')
              number1 = float(event.get('number1', 0))
              number2 = float(event.get('number2', 0))
              if operation == 'add':
                  result = number1 + number2
              elif operation == 'subtract':
                  result = number1 - number2
              elif operation == 'multiply':
                  result = number1 * number2
              elif operation == 'divide':
                  result = number1 / number2 if number2 != 0 else 'undefined'
              else:
                  return {'statusCode': 400, 'body': json.dumps('Invalid operation')}
              return {'statusCode': 200, 'body': json.dumps({'result': result})}
      Runtime: python3.8

  CalculatorLambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub lambda.${AWS::URLSuffix}
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false
      WebsiteConfiguration:
        IndexDocument: calculator-page.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:${AWS::Partition}:s3:::${WebsiteBucket}/calculator-page.html" #${WebsiteBucket} returns just the bucket name.
            
  HtmlUploaderLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_handler
      Role: !GetAtt HtmlUploaderLambdaExecutionRole.Arn
      Runtime: python3.8
      Code:
        ZipFile: |
          import json
          import urllib.request
          import boto3

          def lambda_handler(event, context):
              s3 = boto3.client('s3')
              url = event['ResourceProperties']['HtmlFileUrl']
              response = urllib.request.urlopen(url)
              data = response.read()
              bucket_name = event['ResourceProperties']['BucketName']
              s3.put_object(Bucket=bucket_name, Key='calculator-page.html', Body=data, ContentType='text/html')
              return {'PhysicalResourceId': event.get('PhysicalResourceId', 'HtmlUploaderLambda')}
              
  HtmlUploaderLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub lambda.${AWS::URLSuffix}
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource: !Sub 'arn:${AWS::Partition}:s3:::${WebsiteBucket}/*'
              - Effect: Allow
                Action:
                  - 's3:ListBucket'
                Resource: !Sub 'arn:${AWS::Partition}:s3:::${WebsiteBucket}'

  HtmlUploadCustomResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt HtmlUploaderLambda.Arn
      HtmlFileUrl: !Ref HtmlFileUrl # A Parameter.
      BucketName: !Ref WebsiteBucket # Returns just the bucket's name.

Outputs:
  LambdaFunctionArn:
    Description: The ARN of the Lambda function
    Value: !GetAtt CalculatorLambdaFunction.Arn
  WebsiteURL:
    Description: URL of the S3 website
    Value: !GetAtt WebsiteBucket.WebsiteURL
