---
name: Linter

on: [push]  # yamllint disable-line rule:truthy

jobs:
  pylint_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        #AWS Lambda versions: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
    steps:
      - name: Pull Git Repo
        uses: actions/checkout@v4
      - name: Specficially setup Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install boto3
      - name: Analysing the Python code with pylint
        run: |
          pylint $(git ls-files '*.py')

  yamllint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Git Repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: Analysing the YAML with yamllint
        run: |
          yamllint .
          yamllint $(git ls-files '*.template')

  cfn-lint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Git Repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint
      - name: Analysing CloudFormation templates with cfn-lint
        run: |
          cfn-lint -f pretty -t $(git ls-files '*.template')
